version: "3.9"
services:
  app:
    build: .
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    networks: [demo]
    volumes:
      - ./reports:/app/reports

  app-vuln:
    build: .
    environment:
      - NODE_ENV=development
      - VULN_MODE=on
    ports:
      - "3001:3000"
    networks: [demo]

networks:
  demo:
    driver: bridge
